name: Flutter Testing CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable

            - name: Flutter version
              run: flutter --version

            - name: Install dependencies
              run: flutter pub get

            - name: Analyze code
              run: flutter analyze || true

            - name: Run tests
              run: flutter test
